### PR TITLE
made improvements-in UI/UX, fixed link in newsApi

### LINKED ISSUE #20: Minor ui/ux improvements
1. In the top right corner of the news-card, let's add an external link icon which takes the user to the original article.

image

2. For a better contrast, let's increase the background color opacity on article details box - see screenshot (so instead of `bg-black/30` let's make it `bg-black/60`)

image

3. Let's increase the gap between results (on bigger screens `2rem`, on smaller `1rem`)

image

4. Let's add a bit more spacing below the header

image

### PR DESCRIPTION
**Pull request by SrdjanCukic**
Closes #20

### CODE REVIEW

File: src/UI/Article.jsx [hunk 1]
```diff
@@ -75,7 +84,21 @@ function Article(props) {
         backgroundPosition: 'center',
       }}
     >
-      <div className="absolute bottom-0 left-0 right-0 h-1/2 bg-black/30 p-4 backdrop-blur-lg">
+      <a
+        href={getLink(props)}
+        target="_blank"
+        rel="noopener noreferrer"
+        className={
+          'absolute right-2 top-2 rounded-lg bg-white/[.50] object-right opacity-100'
```
Comment (Ninjaneer87) [inline src/UI/Article.jsx]: Just a few small changes here for more consistency:

To add: `p-1`

To update: `right-0 top-0 bg-black/60`

To remove: `rounded-lg`

File: src/UI/Article.jsx [hunk 2]
```diff
@@ -75,7 +84,21 @@ function Article(props) {
...
+        }
+      >
+        <OpenInNewIcon
+          sx={{
+            color: orange[600],
```
Comment (Ninjaneer87) [inline src/UI/Article.jsx]: Let's use the primary (yellow) color here, the same as in news titles

Hint: 

If you add `text-yellow-500` to the parent (in this case `<a>`) the icon will inherit the color, and you no longer need this `sx` prop

File: src/UI/Article.jsx [hunk 3]
```diff
@@ -75,7 +84,21 @@ function Article(props) {
         backgroundPosition: 'center',
       }}
     >
-      <div className="absolute bottom-0 left-0 right-0 h-1/2 bg-black/30 p-4 backdrop-blur-lg">
+      <a
+        href={getLink(props)}
+        target="_blank"
+        rel="noopener noreferrer"
```
Comment (Ninjaneer87) [inline src/UI/Article.jsx:85]: A heads-up:

For buttons or links without text, or with only icon, it's always good to add `aria-label` attribute for accessibility

[MDN: aria-label](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label)

So in this case you can do

```js
aria-label={title}
```
